In [2]:
import torch
print("working")

working


## Creating Tensor

In [ ]:
## Basic Tensor Creating Func ##
# 1. Empty Tensor -> values from memory
empty_tensor = torch.empty(2, 3)
print(empty_tensor)

# 2. Zeros
zeros_tensor = torch.zeros(2, 3)
print(zeros_tensor)

# 3. Ones
ones_tensor = torch.ones(2, 3)
print(ones_tensor)

# 4. Randon values
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

# Specified Data Type
float_tensor = torch.zeros(2, 3, dtype=torch.float32)
int_tensor = torch.ones(2, 3, dtype=torch.int32)

# ---------------------------------------------------------

## Creating Tensor from Python List ##
data = [[1,2], [3,4]]
tensor_from_list = torch.tensor(data)
print(tensor_from_list)

# ---------------------------------------------------------

## Tensor from Seeding
torch.manual_seed(42) # -> 42 is a popular seed number used to init a seed op, you can use any. 

# random tensor
torch.rand(2, 3)
torch.rand(2, 3)

# using seed
torch.manual_seed(42)
torch.rand(2, 3)


tensor([[1.3220e-32, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7007, 0.8158, 0.8561],
        [0.4838, 0.5436, 0.7346]])
tensor([[1, 2],
        [3, 4]])


## Manipulating Tensor Shapes

### 1. unsqueeze() -> creates dimension
##### unsqueeze(0) -> insert at front | unsqueeze(1) -> insert after first dim 

In [14]:
x = torch.tensor([1,2, 3, 4])

x_unsqueeze0 = x.unsqueeze(0)
x_unsqueeze1 = x.unsqueeze(1)

print(x_unsqueeze0)
print(x_unsqueeze1)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


### 2. squeeze() -> removes dimension of size 1
##### unsqueeze(0) -> insert at front | unsqueeze(0) -> insert after first dim 

### 3. reshape() -> changes dim while keeping the values same

In [18]:
x = torch.arange(12)
print("Original shape:", x.shape)

a = x.reshape(1, 12)
b = x.reshape(2, 6)
c = x.reshape(4, 3)

print(a.shape)
print(b.shape)
print(c.shape)

Original shape: torch.Size([12])
torch.Size([1, 12])
torch.Size([2, 6])
torch.Size([4, 3])


## Managing DT in Tensors

In [ ]:
## Converting an exisitng tensor with .to()
# x = torch.rand((2, 3), dtype=torch.float32)
x = torch.ones(2, 3, dtype=torch.int32)
y = x.to(torch.float32)

print(x.dtype)
print(y.dtype)

## Boolean Tensors -> A boolean tensor is like a filter switch for each element.
scores = torch.tensor([10, 20, 30, 50, 40])
mask = scores > 20

print(mask)
print(mask.dtype)

print(scores[mask])

torch.int32
torch.float32
tensor([False, False,  True,  True,  True])
torch.bool
tensor([30, 50, 40])
