In [22]:
import torch
import torch.nn as nn
import torch.optim as optim

In [21]:
class SimpleModel(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1) #(input_feat, output_feat)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out


In [8]:
# Creating a dataset
features = torch.rand(10, 5)

# Create Model
model = SimpleModel(features.shape[1])

# Call the model for forward pass
print(model(features))

tensor([[0.3159],
        [0.4197],
        [0.3572],
        [0.4375],
        [0.4254],
        [0.3991],
        [0.3210],
        [0.3685],
        [0.3423],
        [0.4312]], grad_fn=<SigmoidBackward0>)


In [9]:
# NN with 15 Weights and 4 Bias with a new HIDDEN LAYER

In [10]:
class NewSimpleNN(nn.Module):
    def __init__(self, input_feat):
        super().__init__()
        self.linear1 = nn.Linear(input_feat, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [14]:
# Creating a DS
features = torch.rand(10, 5)

model = NewSimpleNN(features.shape[1])

model(features)

tensor([[0.4902],
        [0.4944],
        [0.5261],
        [0.4844],
        [0.5021],
        [0.4896],
        [0.4828],
        [0.5154],
        [0.5200],
        [0.5073]], grad_fn=<SigmoidBackward0>)

In [17]:
model.linear1.weight

Parameter containing:
tensor([[-0.2190, -0.3213, -0.0433,  0.2876,  0.2509],
        [ 0.0026, -0.2451,  0.3522, -0.0141,  0.2143],
        [ 0.3327, -0.2009,  0.0735,  0.3949, -0.1579]], requires_grad=True)

In [18]:
model.linear2.weight

Parameter containing:
tensor([[-0.4730,  0.1102, -0.3524]], requires_grad=True)

### Instead of passing the out(y_pred) values through all the methods we can use SEQUENTIAL CONTAINERS to do it.

In [19]:
class NewSimpleNN(nn.Module):
    def __init__(self, input_feat):
        super().__init__()

        self.network(
        nn.Linear(input_feat, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)

        return out

## Full Training Pipeline using in built Loss and Optimizer

In [23]:
# Preapre Data
x = torch.rand(100, 1) * 10
y = x * 2

In [24]:
# Defining the Module
class TrainingPipeline(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(in_features=1, out_features=1)

    def forward(self, x):
        return self.linear(x)

In [25]:
model = TrainingPipeline()

In [29]:
# Loss Func
criterion = nn.MSELoss()

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Setting EPOCH
epoch = 100

In [77]:
# Training loop
for epoch in range(epoch):

    # 1. Forward pass
    predictions = model(x)

    # 2. Loss func
    loss = criterion(predictions, y)

    # 3. Gradient Descent
    optimizer.zero_grad()

    # 4. Backward pass
    loss.backward()

    # 5. Update the weights
    optimizer.step()


In [78]:
# Testing Model
model.eval()

test_input = torch.tensor([[5.0]])

with torch.no_grad():
    test_prediction = model(test_input)

print(f"Input 5.0: | Model Prediction: {test_prediction.item(): .4f}")

Input 5.0: | Model Prediction:  10.0000
