In [2]:
# PyTorch Dataset and DataLoader

## Why mini-batches?
# - Loading the full dataset at once is memory-heavy and slow.
# - Mini-batch gradient descent splits data into small batches, so training is faster and fits in RAM.

## Dataset
# - `Dataset` is responsible for **getting one sample at a time**.
# - Main methods:
#   - `__init__()` → locate/load data
#   - `__len__()` → return total number of samples
#   - `__getitem__(idx)` → return one sample for a given index
# - Best place for sample-level transforms like resize, normalize, etc.

## DataLoader
# - `DataLoader` is responsible for **making batches** from the Dataset.
# - It:
#   1. picks indices
#   2. optionally shuffles them
#   3. calls `Dataset.__getitem__()` for each index
#   4. uses `collate_fn` to combine samples into one batch

## Collate function
# - Takes a list of individual samples and packs them into a batch.
# - Example:
#   - single image: `(3, 224, 224)`
#   - batch of 32 images: `(32, 3, 224, 224)`

## Useful DataLoader options
# - `batch_size` → number of samples per batch
# - `shuffle=True` → randomize sample order
# - `num_workers` → load data in parallel
# - `drop_last=True` → drop the last incomplete batch

## Main idea
# - `Dataset` = fetch data  
# - `DataLoader` = batch and deliver data to the model

In [5]:
import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, Dataset

In [6]:
from sklearn.datasets import make_classification


# Creating a dataset
x, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

print(x, "\n")
print(y)

[[ 1.06833894 -0.97007347]
 [-1.14021544 -0.83879234]
 [-2.8953973   1.97686236]
 [-0.72063436 -0.96059253]
 [-1.96287438 -0.99225135]
 [-0.9382051  -0.54304815]
 [ 1.72725924 -1.18582677]
 [ 1.77736657  1.51157598]
 [ 1.89969252  0.83444483]
 [-0.58723065 -1.97171753]] 

[1 0 0 0 0 1 1 1 1 0]


In [9]:
# Converting x, y in Tensors
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float)

In [24]:
# Creating a Dataset Class

class CustomDataset(Dataset):
    def __init__(self, inputs, outputs):
        self.features = inputs
        self.labels = outputs

    def __len__(self):
        return self.inputs.shape[0]
    
    def __getitem__(self, index):
        return self.inputs[index], self.outputs[index]

In [14]:
dataset = CustomDataset(x, y)

In [21]:
# Creating DataLoader Object (no need to create class)
dataloader = DataLoader(dataset, batch_size=3, shuffle=True, drop_last=True)

In [22]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[-0.7206, -0.9606],
        [-1.1402, -0.8388],
        [-0.9382, -0.5430]])
tensor([0., 0., 1.])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([0., 1., 1.])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.0683, -0.9701],
        [-0.5872, -1.9717]])
tensor([0., 1., 0.])
--------------------------------------------------
