In [1]:
#Numpy Attributes
import numpy as np

In [12]:
arr1 = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print(arr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [20]:
#Shape is used to get to know the SHAPE of a Matrix
#Read as (layer, rows, columns) -> Above matrix has 2 Matrix (1 beside other) + 2 Rows + 2 Columns
arr1.shape

(2, 2, 2)

In [19]:
#ndim used to get the dimestion of the Matrix
#ndim is an "Attribute" thats why we do not use any "()" in front for it
arr1.ndim

3

In [25]:
arr2.size #Size -> total elements in the matrix
arr2.itemsize #Itemsize -> total size of the elemtes used, here INT is 8 Bytes (64Bit)

8

In [28]:
#Dtype -> data type with also Bits
arr1.dtype


dtype('int64')