In [1]:
# Broadcasting 
# It is a concept which is used while performing operations on 2 arrays.
#-------------------------------------------------------------------------
# If the size of array is same then the array will perform as usual but,
# if the size is not same then still it performs the operation but it has 
# some conditions:
# 1. The "y" value should be same of both arrays (x, y).
# 2. If x=1 and y=1 then the operation will take place.

In [2]:
import numpy as np

In [18]:
# Scenario 1
a1 = np.arange(8).reshape(2, 4)
a2 = np.arange(8, 16).reshape(2, 4)
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [17]:
# Scenario 2
a3 = np.arange(9).reshape(3, 3)
a4 = np.arange(3).reshape(1, 3)
a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [23]:
# Here the condition(x=1 and y-should be same) does not match, so it wont broadcast the arrays
a5 = np.arange(3).reshape(1, 3)
a6 = np.arange(16).reshape(4, 4)
a5 + a6

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [25]:
# Here x=1 and n=1 then y==m, so the operation will take place
a7 = np.arange(3).reshape(1, 3)
a8 = np.arange(3).reshape(3, 1)
a7 + a8

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [26]:
# If x=1 and y=1 then operation will take place no matter what 
a9 = np.arange(1).reshape(1, 1)
a10 = np.arange(10).reshape(2, 5)
a9 + a10

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
# Broadcasting even works on differnt dimestions coz the y is same for both the arrays
a11 = np.arange(4)
a12 = np.arange(20).reshape(5, 4)
a11 + a12

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])