In [1]:
import numpy as np

In [16]:
arr1 = np.arange(24).reshape(6, 4) #Reshape(rows, colms), but the size must be rows and cols must be a multiple of Array size
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [23]:
arr1[:,2:3]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [36]:
arr1[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [5]:
arr1 = [[ 0,  1,  2,  3],
 [ 4,  5,  6, 7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23]]

In [7]:
for i in arr1:
    print(i)

[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]
[16, 17, 18, 19]
[20, 21, 22, 23]


In [9]:
for i in np.nditer(arr1):
    print(i)

NameError: name 'np' is not defined