In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

In [4]:
# It does element wise operations
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [7]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [12]:
arr1 > 3 #Get the value of each element (true / false)


array([False, False, False,  True,  True])

In [23]:
# Dot is used to get the dot product, here order of matrix matters
arr2 = np.arange(6).reshape(2,3)
arr3 = np.arange(6, 12).reshape(3,2)
dot_result = arr2.dot(arr3)
print(dot_result) 
print(arr3)

[[ 28  31]
 [100 112]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [24]:
max_num = arr3.max() #Gives max element of the matrix (same with min())
max_axisY = arr3.max(axis=0) #Gives max element from the ROWS
max_axisX = arr3.max(axis=1) #Gives max element from the COLS
print(max_axisY)
print(max_axisX)
print(max_num)

[10 11]
[ 7  9 11]
11


In [31]:
# Can use a lot of built in Math functions like -> mean, median, std, sin
sin_val = np.sin(arr3)
med_val = np.median(arr2)
exp_val = np.exp(arr2)
print(exp_val)
print(med_val)
print(sin_val)

[[  1.           2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003 148.4131591 ]]
2.5
[[-0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849]
 [-0.54402111 -0.99999021]]
