In [5]:
#Creating Numpy / n-d Arrays
import numpy as np


In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [7]:
type(arr1)

numpy.ndarray

In [13]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
arr3 = np.zeros((2, 3))
print(arr3)


[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr4 = np.ones((3, 3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
arr5 = np.identity(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
arr6 = np.arange(10)
print(arr6)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
arr7 = arr6.copy()
print(arr7)


[0 1 2 3 4 5 6 7 8 9]
