In [2]:
import numpy as np

In [3]:
arr1 = np.arange(6).reshape(2,3)
print(arr1)

[[0 1 2]
 [3 4 5]]


In [7]:
# Can use .ravel to convert any n-dim array to 1D array
arr1.ndim # Use ndim to get to know the dim of any array
arr1.ravel()

2


array([0, 1, 2, 3, 4, 5])

In [8]:
#Transpose 
arr1.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [14]:
#Stacking -> can combine 2 arrays
arr2 = np.arange(1, 7).reshape(2, 3)
arr3 = np.arange(7, 13).reshape(2, 3)
arr4 = np.arange(14, 20).reshape(2,3)
np.hstack((arr2, arr3)) # hstack -> horizontal 
np.vstack((arr2, arr3)) # vstack -> vertical 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
# Splitting 
print(arr2)
np.hsplit(arr2, 3) # the value input is how much you want to spli it, it should be equal according to the matrix
np.vsplit(arr2, 2)

[[1 2 3]
 [4 5 6]]


[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [21]:
arr5 = np.random.randint(low=1, high=100, size=20).reshape(4, 5)
print(arr5)

[[29  5 40 22 43]
 [30 48 62 85 57]
 [42  6 61 86 27]
 [21  9 93 46 20]]


In [30]:
mask = arr5 > 10
print(mask) # Mask retruns only the values whoes conditions are true
arr5[arr5 > 10] # This is used to filter 

[[ True False  True  True  True]
 [ True  True  True  True  True]
 [ True False  True  True  True]
 [ True False  True  True  True]]


array([29, 40, 22, 43, 30, 48, 62, 85, 57, 42, 61, 86, 27, 21, 93, 46, 20],
      dtype=int32)

In [31]:
arr5[(arr5 > 50) & (arr5%2!=0)] # Here we use bitwise & not the "and"

array([85, 57, 61, 93], dtype=int32)

In [37]:
arr5[(arr5 > 50) & (arr5%2!=0)]=0 #Changes the value of those elements who satisfies the condition
print(arr5) 

[[29  5 40 22 43]
 [30 48 62  0  0]
 [42  6  0 86 27]
 [21  9  0 46 20]]
